### ISSUE TITLE
Automatically clean region

### ISSUE THREAD

**Issue by leandr0ck** [jfairbank/marionette.component#42]
would be good that when you call the "showIn", all the views into the region are removed automatically

(sorry for my english)

**Comment by jfairbank** [comment]
Hi, @lean. I'm leaning on Marionette itself to manage this for me. When I call `region.show(view)`, Marionette manages cleaning out any old view:

https://github.com/marionettejs/backbone.marionette/blob/master/src/region.js#L224-L236

However, it would be good to add some tests to confirm this works correctly. Thanks!
