### ISSUE TITLE
Using components with marionette-wires and browserify

### ISSUE THREAD

**Issue by dnewkerk** [jfairbank/marionette.component#44]
Hi Jeremy, really excited to try this out. It took me a while to figure this out so thought I would share in case other people need help. I recently began using the [marionette-wires](https://github.com/thejameskyle/marionette-wires) starter app, and by extension browserify (until now I had not used javascript modules).

To configure marionette.component in your app with browserify, follow these steps:

Add `"marionette.component": "^0.0.1"` to "dependencies" in your `package.json` file and run `npm install`

Add the following to the marionette-wires `plugins.js` at the root of the app:

``` javascript
var Marionette = require('backbone.marionette');
Marionette.Component = require('marionette.component');
```

I like to add base versions of classes and views, so add a `/common/component.js` file with the following:

``` javascript
var Marionette = require('backbone.marionette');
module.exports = Marionette.Component;
```

I tested it by creating a file called `my_component.js` at the app root with the following:

``` javascript
var _ = require('lodash');
var ItemView = require('./common/item-view');
var Component = require('./common/component');

var MyView = ItemView.extend({
  template: _.template('Hello World')
});

var MyComponent = Component.extend({
  viewClass: MyView
});

module.exports = new MyComponent();
```

And lastly, I initialized my new component from `main.js`:

``` javascript
var myComponent = require('./my_component');
myComponent.showIn(app.layout.content);
```

Upon reloading the page, "Hello World" appears in the content region! Hope this helps someone.

**Comment by jfairbank** [comment]
Hey @dnewkerk. Thanks for the support and little write up here! I'm glad it wasn't too painful to hook up with browserify. This would be a nice little section in the README or a separate doc if you want to PR it.

If you have any suggestions for the lib while you play with it, let me know.

Thanks!
